# Generated by Django 5.1 on 2025-10-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Chave da sessão Django', max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do navegador')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do cliente', null=True)),
            ],
            options={
                'verbose_name': 'Sessão de Cliente',
                'verbose_name_plural': 'Sessões de Clientes',
                'ordering': ['-last_activity'],
            },
        ),
    ]
