# Generated by Django 5.1 on 2025-10-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao_online', 'Cartão (Online)'), ('cartao_presencial', 'Cartão (Presencial)')], db_index=True, default='pix', max_length=20),
        ),
    ]
