# Generated by Django 5.1 on 2025-10-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_integration_failed',
            field=models.BooleanField(default=False, help_text='Indica se a integração com o gateway de pagamento falhou'),
        ),
    ]
