# Generated by Django 5.1 on 2025-11-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('quantity_orders', models.IntegerField(default=0)),
                ('quantity_orders_status_completed', models.IntegerField(default=0)),
                ('quantity_orders_status_cancelled', models.IntegerField(default=0)),
                ('quantity_orders_status_pending', models.IntegerField(default=0)),
                ('quantity_orders_late', models.IntegerField(default=0)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenue_pending_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity_products', models.IntegerField(default=0)),
                ('quantity_products_active', models.IntegerField(default=0)),
                ('quantity_products_inactive', models.IntegerField(default=0)),
                ('ticket_medio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxa_conclusao', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('taxa_cancelamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relat�rio Di�rio',
                'verbose_name_plural': 'Relat�rios Di�rios',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='reports_dai_date_140076_idx'), models.Index(fields=['created_at'], name='reports_dai_created_62f9f9_idx')],
            },
        ),
    ]
