# Generated by Django 5.1 on 2025-10-19 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, help_text='CPF do cliente (opcional, mas recomendado)', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('address', models.TextField(verbose_name='Endereço Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('user', models.OneToOneField(help_text='Usuário vinculado (não é superuser)', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente Fiel',
                'verbose_name_plural': 'Clientes Fiéis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['cpf'], name='customers_c_cpf_93e83b_idx'), models.Index(fields=['is_active', 'created_at'], name='customers_c_is_acti_3160aa_idx')],
            },
        ),
    ]
