# Generated by Django 5.1 on 2025-10-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('cpf', models.CharField(blank=True, help_text='CPF do cliente', max_length=14, null=True)),
                ('address', models.TextField()),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao_online', 'Cartão (Online)'), ('cartao_presencial', 'Cartão (Presencial)')], db_index=True, default='pix', max_length=20)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado/Devolvido')], db_index=True, default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='ID do pagamento no MercadoPago', max_length=255, null=True)),
                ('payment_url', models.URLField(blank=True, help_text='URL do pagamento no MercadoPago (para cartão)', null=True)),
                ('payment_integration_failed', models.BooleanField(default=False, help_text='Indica se a integração com o gateway de pagamento falhou')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('client_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.clientsession')),
                ('customer', models.ForeignKey(blank=True, help_text='Cliente fiel que fez o pedido (se logado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='orders_orde_status_c50fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status'], name='orders_orde_created_49d91d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'payment_status'], name='orders_orde_payment_7a00e5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone', 'created_at'], name='orders_orde_phone_ba307f_idx'),
        ),
    ]
